require: rubocop-rspec

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
  Max: 20

RSpec/BeEql:
  Enabled: false
