AllCops:
  # Additional exclude patterns for files that should not be analyzed.
  # These extend the default RuboCop exclude patterns:
  # https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
  Exclude:
    - 'script/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/ScopeArgs:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Rails/Validation:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/CollectionMethods:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/MutableConstant:
  Enabled: true

Metrics/MethodLength:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  ExcludedMethods: ['describe', 'context', 'define', 'factory', 'namespace']

Metrics/AbcSize:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  AutoCorrect: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true
  AutoCorrect: true
